services:
  php:
    build:
      context: .docker/
      dockerfile: php.dockerfile
      args:
        uid: 1000
        user: throyan
    volumes:
      - "./:/var/www"
    command: "php app.php input.txt"

